### ISSUE TITLE
try use this in ionic project

### ISSUE THREAD

**Issue by datpp** [Waracle/steps-cordova-ios#2]
I tried to run command `cordova build ios` in my local, it works. but same command in Bitrise env make this error. can you please check ?

===> Running 'cordova build ios --verbose'
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml for saved platforms that haven't been added to the project
 Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.
Checking for any plugins added to the project that have not been installed in ios platform
Reinstalling missing plugin cordova-plugin-console in ios platform
Error: Error
    at Object.parseProjectFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:271:19)
    at PlatformApiPoly.removePlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:302:71)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:189:24
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nhammond101** [comment]
Hi @datpp, i was unable to recreate the issue and I use this build step in a few of our cordova and ionic builds.  Do you have the version set in the config.xml?

**Comment by datpp** [comment]
hi @nhammond101 ,

I know the root cause of the issue, has been fixed.

My solutions that's remove `platform` folder out the source code, store `.xproject` file (use to store config of ios project) to other place.

When building with Bitrise I add command `cordova build ios` to project. After done will copy `.xproject` overwrite to the `platform/ios`.

**Comment by nhammond101** [comment]
@datpp glad to hear you got it sorted :)
